name:
	{{cookiecutter.repo_name}}
channels:
	- base
	- anaconda
	- conda-forge
{% if cookiecutter.workflow_automation == "Snakemake" %}
	- bioconda
{% endif %}
dependencies:
{% if cookiecutter.workflow_automation == "Snakemake" %}
	- snakemake
{% endif %}
	

