name:
	{{cookiecutter.repo_name}}
channels:
	- base
	- conda-forge
	- anaconda
{%- if cookiecutter.workflow_automation == "Snakemake" -%}
	- bioconda
{% endif %}
dependencies:
{%- if cookiecutter.notebooks == "Yes" -%}
	- jupyter
{% endif %}
{%- if cookiecutter.workflow_automation == "Snakemake" -%}
	- snakemake
{% endif %}